try:
    print()
except Exception as e:
    x = e
    #   ^ defined: 3
